/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as ItensRouteImport } from './routes/itens'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotasFiscaisRouteImport } from './routes/notas-fiscais'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ItensRoute = ItensRouteImport.update({
  id: '/itens',
  path: '/itens',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasFiscaisRoute = NotasFiscaisRouteImport.update({
  id: '/notas-fiscais',
  path: '/notas-fiscais',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/empresas': typeof EmpresasRoute
  '/itens': typeof ItensRoute
  '/login': typeof LoginRoute
  '/notas-fiscais': typeof NotasFiscaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/empresas': typeof EmpresasRoute
  '/itens': typeof ItensRoute
  '/login': typeof LoginRoute
  '/notas-fiscais': typeof NotasFiscaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/empresas': typeof EmpresasRoute
  '/itens': typeof ItensRoute
  '/login': typeof LoginRoute
  '/notas-fiscais': typeof NotasFiscaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/clientes' | '/empresas' | '/itens' | '/login' | '/notas-fiscais'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clientes' | '/empresas' | '/itens' | '/login' | '/notas-fiscais'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/empresas'
    | '/itens'
    | '/login'
    | '/notas-fiscais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  EmpresasRoute: typeof EmpresasRoute
  ItensRoute: typeof ItensRoute
  LoginRoute: typeof LoginRoute
  NotasFiscaisRoute: typeof NotasFiscaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itens': {
      id: '/itens'
      path: '/itens'
      fullPath: '/itens'
      preLoaderRoute: typeof ItensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas-fiscais': {
      id: '/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/notas-fiscais'
      preLoaderRoute: typeof NotasFiscaisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  EmpresasRoute: EmpresasRoute,
  ItensRoute: ItensRoute,
  LoginRoute: LoginRoute,
  NotasFiscaisRoute: NotasFiscaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
